apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pathfinder-mainnet-cert
spec:
  secretName: pathfinder-mainnet-tls

  dnsNames:
  - pathfinder.mainnet.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer
