---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pathfinder-sepolia-cert
spec:
  secretName: pathfinder-sepolia-tls

  dnsNames:
    - pathfinder.sepolia.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer