apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iosis-tech-mainnet-starknet-node

resources:
- deployment.yaml
# - issuer.yaml
# - certificates.yaml
# - pvc.yaml

configMapGenerator:
- name: pathfinder-config
  literals:
  - RUST_LOG=info
  - PATHFINDER_RPC_ROOT_VERSION=v07
  - PATHFINDER_NETWORK=mainnet
  - PATHFINDER_GATEWAY_REQUEST_TIMEOUT=10000
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: pathfinder-secret
  envs:
  - secret.env
  options:
    disableNameSuffixHash: true
