apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pathfinder-pvc
spec:
  storageClassName: rook-ceph-ec-hdd-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
